config/routes.rb
Rails.application.routes.draw do
  resources :clients do
    resources :pets do
      resources :histories
      #resources :histories, only: [:index, :create, :new]
      #resources :histories, shallow: true
    end
  end

  root 'clients#index'

  #resources :histories, except: [:index, :create, :new]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :pets, dependent: :destroy

  def to_s #Devolver el nombre del dueño
    return name
  end

  def pets_count #Metodo para contar la cantidad de mascotas
    self.pets.count
  end

end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :histories, dependent: :destroy
  belongs_to :client
  
  def to_s #Devolver el nombre de la mascota
    return name
  end

  def histories_count #Metodo para contar la cantidad de veces que ha visitado al vet
    self.histories.count
  end

  def average_weight #Metodo del promedio de los pesos de la mascota
    # self.histories.pluck(:weight).sum / self.histories_count Otra forma de hacer lo mismo de abajo
    self.histories.sum(:weight) / self.histories_count 
  end

  def average_height #Metodo del promedio de las alturas de la mascota
    self.histories.sum(:height) / self.histories_count
  end

  def max_weight
    self.histories.maximum(:weight)
  end

  def max_height
    self.histories.maximum(:height)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: %i[ show edit update destroy ]
  before_action :set_pet #De esta forma se ve en todas las vistas
  before_action :set_client

  # GET /histories or /histories.json
  def index
    #@histories = @client.pets.find(@pet.id).histories Muy compleja -.-
    @histories = @pet.histories
  end

  # GET /histories/1 or /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = @pet.histories.build
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories or /histories.json
  def create
    @history = @pet.histories.build(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to [@pet.client, @pet, @history], notice: "History was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1 or /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params.merge(pet: @pet))
        format.html { redirect_to [@pet.client, @pet, @history], notice: "History was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1 or /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to [@pet.client, @pet, @history], notice: "History was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    def set_pet
      @pet = Pet.find(params[:pet_id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Only allow a list of trusted parameters through.
    def history_params
      params.require(:history).permit(:date, :weight, :height, :description)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy ]
  before_action :set_client
  # GET /pets or /pets.json
  def index
    @pets = @client.pets
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = @client.pets.build
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = @client.pets.build(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to [@client, @pet], notice: "Pet was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params.merge(pet: @pet))
        format.html { redirect_to [@client, @pet], notice: "Pet was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to [@client, @pet], notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Pets count</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= client.pets_count %></td> <!-- Llamada del metodo para contar la cantidad de mascotas de un cliente -->
        <td><%= link_to 'Pets', client_pets_path(client) %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

 <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Max. Weight</th>
      <th>Max. Height</th>
    </tr>
  </thead>
  <tbody>
    <% @client.pets.each do |pet| %>
    <tr>
      <td><%= pet.name %></td>
      <td><%= pet.max_weight %></td>
      <td><%= pet.max_height %></td>
    </tr>
    <% end %>
  </tbody>
</table> 

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/histories/_form.html.erb
<%= form_with(model: [@client, @pet, history], local: true) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', [@client, @pet, @history] %> |
<%= link_to 'Back', client_pet_histories_path(@client, @pet) %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Description</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.date %></td>
        <td><%= history.weight %></td>
        <td><%= history.height %></td>
        <td><%= history.description %></td>
        <td><%= link_to history.pet, client_pets_path(@client) %></td>
        <td><%= link_to 'Show', [@client, @pet, history] %></td>
        <td><%= link_to 'Edit', edit_client_pet_history_path(@client, @pet, history) %></td>
        <td><%= link_to 'Destroy', [@client, @pet, history], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_client_pet_history_path(@client, @pet) %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', client_pet_histories_path(@client, @pet) %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @history.date %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @history.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @history.height %>
</p>

<p>
  <strong>Description:</strong>
  <%= @history.description %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @history.pet %>
</p>

<%= link_to 'Edit', edit_client_pet_history_path(@client, @pet, @history) %> |
<%= link_to 'Back', client_pet_histories_path(@client, @pet) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: [@client, pet], local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, start_year: 1940 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', [@client, @pet] %> |
<%= link_to 'Back', client_pets_path(@client) %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Birthday</th>
      <th>Owner</th>
      <th>Histories count</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.birthday %></td>
        <td><%= link_to pet.client, clients_path %></td>
        <td><%= pet.histories_count %></td> <!-- Llamada del metodo para contar las veces de visita al vet -->
        <td><%= link_to 'History', client_pet_histories_path(@client, pet) %></td>
        <td><%= link_to 'Show', [@client, pet] %></td>
        <td><%= link_to 'Edit', edit_client_pet_path(@client, pet) %></td>
        <td><%= link_to 'Destroy', [@client, pet], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_client_pet_path(@client) %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', client_pets_path(@client) %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @pet.birthday %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @pet.client %>
</p>

<br/>

<table class="table">
  <thead>
    <tr>
      <th>Average Weight</th>
      <th>Average Height</th>
      <th>Max. Weight</th>
      <th>Max. Height</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @pet.average_weight %></td>
      <td><%= @pet.average_height %></td>
      <td><%= @pet.max_weight %></td>
      <td><%= @pet.max_height %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_client_pet_path(@client, @pet) %> |
<%= link_to 'Back', client_pets_path(@client) %>